import type { Metadata } from "next"
import { Inter as FontInter, Poppins as FontPoppins } from "next/font/google"
import { cn } from "@/lib/utils"

import "./globals.css"
import { auth } from "@/auth"
import { SessionProvider } from "next-auth/react"
import { Toaster } from "sonner"

const fontSans = FontInter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={cn(
            "h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}
        >
          <Toaster richColors />
          {children}
        </body>
      </html>
    </SessionProvider>
  )
}
